name: new site trial and error
favicon: null
layout_spectrum: 0.31675
typography_spectrum: 0.20007949066348374
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c82806'
    - '#fefefe'
    - '#18110b'
    - '#4f5356'
    - '#fe8a3a'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
